apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: elasticsearch-node-template.yaml
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: elasticsearch
    name: elasticsearch
  spec:
    replicas: 1
    selector:
      app: elasticsearch
      deploymentconfig: elasticsearch
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: elasticsearch
          deploymentconfig: elasticsearch
      spec:
        containers:
        - env:
          - name: LOG_LEVEL
            value: INFO
          - name: NODE_QUORUM
            value: "1"
          - name: ES_CLUSTER_SERVICE
            value: elasticsearch.es-test.svc
          - name: ES_JAVA_OPTS
            value: -Xms8g -Xmx8g -XX:+UnlockDiagnosticVMOptions -XX:+PrintCompressedOopsMode
              -Dnetworkaddress.cache.ttl=1 -Djava.net.preferIPv4Stack=true
          image: 172.30.112.51:5000/es-test/elasticsearch-rhel7-sma@sha256:035ec66faac5f54cfeaf5a8374ab8dc7edd0db0fc0c34cdc02344b0ce41f9348
          imagePullPolicy: Always
          name: elasticsearch
          ports:
          - containerPort: 9200
            protocol: TCP
          - containerPort: 9300
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /_cluster/health?local=true
              port: 9200
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: vol-elastic-data
        dnsPolicy: ClusterFirst
        nodeSelector:
          nodenumber: "11"
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /usr/local/elasticsearch/data
          name: vol-elastic-data
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - elasticsearch
        from:
          kind: ImageStreamTag
          name: elasticsearch-rhel7-sma:latest
          namespace: es-test
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
