apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-api
  labels:
    app: elasticsearch
    role: client
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch
    role: client
  ports:
  - name: api
    port: 9200
    protocol: TCP
